Repository 12-team-project/My-Media, pull requests merged in 2023-10, with the labels that each got.

#22 [디테일프래그먼트]좋아요버튼 로티
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/java/com/example/my_media/detail/VideoDetailFragment.kt
  app/src/main/java/com/example/my_media/main/MainActivity.kt
  app/src/main/java/com/example/my_media/main/MainSharedViewModel.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoAdapter.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoViewModel.kt
  app/src/main/java/com/example/my_media/util/ToastUtil.kt
  app/src/main/res/layout/favorite_item.xml
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/fragment_video_detail.xml
  app/src/main/res/raw/like.json
  app/src/main/res/values/strings.xml
Labels: fix

#29 [search&deatail]서치아이템클릭 했을 때 디테일로
  app/src/main/java/com/example/my_media/detail/VideoDetailFragment.kt
  app/src/main/java/com/example/my_media/home/HomeViewModel.kt
  app/src/main/java/com/example/my_media/search/SearchFragment.kt
  app/src/main/java/com/example/my_media/search/SearchListAdapter.kt
  app/src/main/java/com/example/my_media/search/SearchModel.kt
  app/src/main/java/com/example/my_media/search/SearchViewModel.kt
Labels: feat

#31 [HomeFragement] 카테고리별 인기동영상
  .idea/sonarlint/issuestore/index.pb
  .idea/sonarlint/securityhotspotstore/index.pb
  app/src/main/java/com/example/my_media/data/PopularVideosResponse.kt
  app/src/main/java/com/example/my_media/data/YoutubeRemoteDataSource.kt
  app/src/main/java/com/example/my_media/data/YoutubeRepository.kt
  app/src/main/java/com/example/my_media/detail/VideoDetailFragment.kt
  app/src/main/java/com/example/my_media/home/HomeFragment.kt
  app/src/main/java/com/example/my_media/home/HomeViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: feat

#32 [Refactoring] UI 통일 및 파일 이름 변경, MainActivity 코드 MainViewModel로 이동
  app/src/main/java/com/example/my_media/detail/VideoDetailFragment.kt
  app/src/main/java/com/example/my_media/main/MainActivity.kt
  app/src/main/java/com/example/my_media/main/MainViewModel.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoAdapter.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoFragment.kt
  app/src/main/java/com/example/my_media/search/SearchListAdapter.kt
  app/src/main/res/drawable/border_search.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_video_detail.xml
  app/src/main/res/layout/item_favorite.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/layout/item_subscribe.xml
  app/src/main/res/layout/item_videos.xml
  app/src/main/res/layout/progress_search.xml
  app/src/main/res/values/strings.xml
Labels: merge

#35 [홈,서치,마이비디오] 어댑터에 애니매이션 효과추가
  app/src/main/java/com/example/my_media/detail/VideoDetailFragment.kt
  app/src/main/java/com/example/my_media/home/HomeFragment.kt
  app/src/main/java/com/example/my_media/home/popular/HomePopularListAdapter.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoAdapter.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoFragment.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoViewModel.kt
  app/src/main/java/com/example/my_media/search/SearchFragment.kt
  app/src/main/java/com/example/my_media/search/SearchListAdapter.kt
  app/src/main/res/anim/slide_in_row.xml
  app/src/main/res/drawable/ic_back_btn.xml
  app/src/main/res/drawable/test2.png
  app/src/main/res/drawable/test3.jpg
  app/src/main/res/drawable/test4.jpg
  app/src/main/res/drawable/test5.jpg
  app/src/main/res/drawable/test6.jpg
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/fragment_video_detail.xml
  app/src/main/res/raw/profile.json
Labels: feat

#38 Bugs Fix
  app/src/main/java/com/example/my_media/detail/VideoDetailFragment.kt
  app/src/main/java/com/example/my_media/home/HomeFragment.kt
  app/src/main/java/com/example/my_media/home/HomeViewModel.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoFragment.kt
  app/src/main/java/com/example/my_media/search/SearchViewModel.kt
  app/src/main/res/drawable/ic_no_image.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/values/strings.xml
Labels: fix

#40 SharedPreferences 저장 & 불러오기
  app/src/main/java/com/example/my_media/mypage/MyVideoFragment.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoViewModel.kt
  app/src/main/java/com/example/my_media/util/ContextProvider.kt
  app/src/main/res/values/strings.xml
Labels: feat

#43 Feature/popular video
  .idea/sonarlint/issuestore/index.pb
  .idea/sonarlint/securityhotspotstore/index.pb
  app/src/main/java/com/example/my_media/home/HomeFragment.kt
Labels: fix

#44 [mainSharedViewModel]좋아요상태 저장,로드
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/my_media/detail/VideoDetailFragment.kt
  app/src/main/java/com/example/my_media/main/MainSharedViewModel.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoAdapter.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoFragment.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoViewModel.kt
  app/src/main/res/values/strings.xml
Labels: feat

#46 [Feat] : Retrofit을 이용해서 조회수,좋아요갯수 불러와서 디테일에 표시
  app/src/main/java/com/example/my_media/data/PopularVideosResponse.kt
  app/src/main/java/com/example/my_media/data/SearchVideoResponse.kt
  app/src/main/java/com/example/my_media/data/YoutubeRemoteDataSource.kt
  app/src/main/java/com/example/my_media/detail/VideoDetailFragment.kt
  app/src/main/java/com/example/my_media/home/HomeViewModel.kt
  app/src/main/java/com/example/my_media/home/popular/HomePopularModel.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoAdapter.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoFragment.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoModel.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoViewModel.kt
  app/src/main/java/com/example/my_media/search/SearchModel.kt
  app/src/main/java/com/example/my_media/search/SearchViewModel.kt
  app/src/main/res/drawable/ic_back_btn.xml
  app/src/main/res/drawable/test.jpg
  app/src/main/res/drawable/test2.png
  app/src/main/res/drawable/test3.jpg
  app/src/main/res/drawable/test4.jpg
  app/src/main/res/drawable/test5.jpg
  app/src/main/res/drawable/test6.jpg
  app/src/main/res/layout/fragment_video_detail.xml
  app/src/main/res/values/strings.xml
Labels: feat

#48 HomeFragment 탭 변경 시 버그 수정 및 일부 코드 리팩토링
  app/src/main/java/com/example/my_media/home/HomeFragment.kt
  app/src/main/java/com/example/my_media/home/HomeViewModel.kt
  app/src/main/java/com/example/my_media/main/MainActivity.kt
  app/src/main/java/com/example/my_media/util/UserManager.kt
Labels: fix

#50 [HomeFragment] CoordinatorLayout 변경
  app/src/main/java/com/example/my_media/home/HomeViewModel.kt
  app/src/main/java/com/example/my_media/main/MainActivity.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_video_detail.xml
  app/src/main/res/values/strings.xml
Labels: fix
