Repository 12-team-project/My-Media, pull requests merged in 2023-09, with the labels that each got.

#3 Feature/my video
  app/build.gradle
  app/src/main/java/com/example/my_media/detail/VideoDetailFragment.kt
  app/src/main/java/com/example/my_media/main/MainActivity.kt
  app/src/main/java/com/example/my_media/main/MainSharedViewModel.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoAdapter.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoFragment.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoModel.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoViewModel.kt
  app/src/main/res/drawable/backimg.jpg
  app/src/main/res/drawable/github.png
  app/src/main/res/drawable/notion.png
  app/src/main/res/drawable/test.jpg
  app/src/main/res/font/cookie.ttf
  app/src/main/res/layout/favorite_item.xml
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/values/strings.xml
Labels: feat

#5 [Design] HomeFragment
  app/build.gradle
  app/src/main/java/com/example/my_media/data/Repository.kt
  app/src/main/java/com/example/my_media/home/HomeFragment.kt
  app/src/main/java/com/example/my_media/home/HomeListAdapter.kt
  app/src/main/java/com/example/my_media/home/HomeModel.kt
  app/src/main/java/com/example/my_media/home/HomeViewModel.kt
  app/src/main/res/color/pressed_chip.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_videos.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: design

#6 [디테일,마이프래그먼트]화면 뷰모델 구현
  app/build.gradle
  app/src/main/java/com/example/my_media/detail/VideoDetailFragment.kt
  app/src/main/java/com/example/my_media/home/HomeFragment.kt
  app/src/main/java/com/example/my_media/home/HomeListAdapter.kt
  app/src/main/java/com/example/my_media/main/MainSharedViewModel.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoAdapter.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoFragment.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoModel.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoViewModel.kt
  app/src/main/res/drawable/ic_like.xml
  app/src/main/res/drawable/ic_mtlike.xml
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/fragment_video_detail.xml
  app/src/main/res/values/strings.xml
Labels: fragment

#8 Feature/search
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/my_media/data/Reponse.kt
  app/src/main/java/com/example/my_media/data/Response.kt
  app/src/main/java/com/example/my_media/data/RetrofitClient.kt
  app/src/main/java/com/example/my_media/data/RetrofitInterface.kt
  app/src/main/java/com/example/my_media/main/MainActivity.kt
  app/src/main/java/com/example/my_media/search/SearchFragment.kt
  app/src/main/java/com/example/my_media/search/SearchListAdapter.kt
  app/src/main/java/com/example/my_media/search/SearchModel.kt
  app/src/main/java/com/example/my_media/search/SearchViewModel.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/search_recyclerview_item.xml
Labels: fragment

#9 [홈] 인기 동영상 구현
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/my_media/data/PopularVideosResponse.kt
  app/src/main/java/com/example/my_media/data/RemoteDataSource.kt
  app/src/main/java/com/example/my_media/data/Reponse.kt
  app/src/main/java/com/example/my_media/data/Repository.kt
  app/src/main/java/com/example/my_media/data/RetrofitClient.kt
  app/src/main/java/com/example/my_media/data/RetrofitInterface.kt
  app/src/main/java/com/example/my_media/home/HomeFragment.kt
  app/src/main/java/com/example/my_media/home/HomeListAdapter.kt
  app/src/main/java/com/example/my_media/home/HomeModel.kt
  app/src/main/java/com/example/my_media/home/HomeViewModel.kt
  app/src/main/res/color/pressed_chip.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_videos.xml
Labels: feat

#13 [DetailFragment]좋아요기능and추가시myVideo로이동
  app/src/main/java/com/example/my_media/detail/VideoDetailFragment.kt
  app/src/main/java/com/example/my_media/home/HomeFragment.kt
  app/src/main/java/com/example/my_media/home/HomeViewModel.kt
  app/src/main/java/com/example/my_media/home/popular/HomePopularListAdapter.kt
  app/src/main/java/com/example/my_media/home/popular/HomePopularModel.kt
  app/src/main/java/com/example/my_media/main/MainSharedViewModel.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoAdapter.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoFragment.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoModel.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoViewModel.kt
  app/src/main/res/layout/favorite_item.xml
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/fragment_video_detail.xml
  app/src/main/res/values/colors.xml
Labels: feat

#18 [홈] OAuth 인증 및 구독리스트 출력
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/my_media/data/SubscribeResponse.kt
  app/src/main/java/com/example/my_media/data/YoutubeRemoteDataSource.kt
  app/src/main/java/com/example/my_media/home/HomeViewModel.kt
  app/src/main/java/com/example/my_media/home/popular/HomePopularListAdapter.kt
  app/src/main/java/com/example/my_media/home/subscribe/HomeSubscribeListAdapter.kt
  app/src/main/java/com/example/my_media/main/MainActivity.kt
  app/src/main/res/drawable/ic_no_image.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_subscribe.xml
Labels: fix

#19 [디테일frag]좋아요 했을때 리스트에 추가되게
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/example/my_media/detail/VideoDetailFragment.kt
  app/src/main/java/com/example/my_media/main/MainSharedViewModel.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoAdapter.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoFragment.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoModel.kt
  app/src/main/java/com/example/my_media/mypage/MyVideoViewModel.kt
  app/src/main/java/com/example/my_media/util/ToastUtil.kt
  app/src/main/res/layout/fragment_my_video.xml
Labels: fix
